// <auto-generated />
using DristisBooksStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DristisBooks.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext)), Migration("20231128151232_add-migration AddCoverTypeToDb")]
    internal class addmigrationAddCoverTypeToDbBaseBaseBase : addmigrationAddCoverTypeToDbBaseBaseBaseBase
    {
    }
}