// <auto-generated />
using System;
using DristisBooksStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DristisBooks.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231128151232_add-migration AddCoverTypeToDb")]
    partial class addmigrationAddCoverTypeToDb : addmigrationAddCoverTypeToDbBaseBaseBase
    {
    }
}
